version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/l1"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/l1/independent-light-client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
