#!/usr/bin/env node
// Reproducible build of website/app/vendor/* from the exact versions pinned in package-lock.json.
//   npm ci && node build-vendor.mjs          -> writes the bundles + VENDOR.json
//   npm ci && node build-vendor.mjs --check  -> fails if the committed files differ from a fresh build
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, '..', '..', 'website', 'app', 'vendor');
const check = process.argv.includes('--check');
const lock = JSON.parse(readFileSync(join(here, 'package-lock.json'), 'utf8'));
const pkg = (name) => {
  const entry = lock.packages[`node_modules/${name}`];
  if (!entry) throw new Error(`${name} missing from package-lock.json`);
  return { name, version: entry.version, resolved: entry.resolved, integrity: entry.integrity };
};

const bundles = [
  { file: 'noble-scure.js', entry: 'entry-crypto.js', packages: ['@noble/curves', '@noble/hashes', '@scure/base', '@scure/bip32', '@scure/bip39'] },
  { file: 'qr.js', entry: 'entry-qr.js', packages: ['qr'] }
];

const sri = (bytes) => `sha384-${createHash('sha384').update(bytes).digest('base64')}`;
const manifest = { comment: 'Generated by tools/pwa-wallet/build-vendor.mjs. Do not edit by hand.', esbuild: pkg('esbuild').version, bundles: [] };
let failed = false;
for (const bundle of bundles) {
  const packages = bundle.packages.map(pkg);
  const banner = [
    '/*! ZyronChain PWA vendored bundle (do not edit; rebuild with tools/pwa-wallet). Licenses: website/app/vendor/LICENSES.txt',
    ...packages.map((p) => ` *  ${p.name}@${p.version} ${p.integrity}`),
    ' */'
  ].join('\n');
  const result = await build({
    entryPoints: [join(here, bundle.entry)],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020', 'safari15', 'chrome100'],
    minify: false,
    legalComments: 'inline',
    charset: 'utf8',
    banner: { js: banner },
    write: false,
    absWorkingDir: here,
    logLevel: 'warning'
  });
  const bytes = Buffer.from(result.outputFiles[0].contents);
  const target = join(outDir, bundle.file);
  if (check) {
    let current = null;
    try { current = readFileSync(target); } catch {}
    if (!current || !current.equals(bytes)) { console.error(`vendor bundle differs from a fresh build: ${bundle.file}`); failed = true; }
  } else {
    writeFileSync(target, bytes);
  }
  manifest.bundles.push({ file: bundle.file, integrity: sri(bytes), sha256: createHash('sha256').update(bytes).digest('hex'), packages });
}
const manifestText = `${JSON.stringify(manifest, null, 2)}\n`;
const manifestPath = join(outDir, 'VENDOR.json');
if (check) {
  if (readFileSync(manifestPath, 'utf8') !== manifestText) { console.error('VENDOR.json is stale'); failed = true; }
  if (failed) process.exit(1);
  console.log('pwa-vendor-reproducible-ok');
} else {
  writeFileSync(manifestPath, manifestText);
  console.log(manifestText);
}
