(() => {
  'use strict';

  const RELEASE_REF = 'a3512f26b32d8d8c71402d0f59c1baeb44a5b3a0';
  const REPO_URL = 'https://github.com/zyron249/-zyronchain.git';

  const $ = (id) => document.getElementById(id);
  const shellQuote = (value) => `'${String(value).replace(/'/g, `'"'"'`)}'`;

  const cleanLabel = (value) => {
    const cleaned = String(value || '').trim().toLowerCase().replace(/[^a-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '');
    return cleaned.slice(0, 40) || 'validator-1';
  };

  const validPort = (value) => {
    const port = Number.parseInt(String(value), 10);
    return Number.isInteger(port) && port >= 1024 && port <= 65535 ? port : null;
  };

  const encodeBase64Utf8 = (text) => {
    const bytes = new TextEncoder().encode(text);
    let binary = '';
    const chunk = 0x8000;
    for (let i = 0; i < bytes.length; i += chunk) {
      binary += String.fromCharCode(...bytes.subarray(i, i + chunk));
    }
    return btoa(binary);
  };

  const platformBootstrap = (platform) => {
    if (platform === 'termux') {
      return `command -v pkg >/dev/null 2>&1 || { echo "Run this script inside Termux." >&2; exit 1; }\npkg update -y\npkg install -y git nodejs-lts`;
    }
    if (platform === 'wsl') {
      return `grep -qi microsoft /proc/version 2>/dev/null || echo "Note: this launcher is intended for Windows via WSL2."\ncommand -v git >/dev/null 2>&1 || { echo "Install git inside WSL2 first." >&2; exit 1; }\ncommand -v node >/dev/null 2>&1 || { echo "Install Node.js 22+ inside WSL2 first." >&2; exit 1; }`;
    }
    return `command -v git >/dev/null 2>&1 || { echo "git is required." >&2; exit 1; }\ncommand -v node >/dev/null 2>&1 || { echo "Node.js 22+ is required." >&2; exit 1; }`;
  };

  const nodeVersionCheck = `NODE_MAJOR="$(node -p "process.versions.node.split('.')[0]")"\nif [ "$NODE_MAJOR" -lt 22 ]; then echo "Node.js 22+ is required; found $(node --version)." >&2; exit 1; fi`;

  const repoSetup = `ROOT="$HOME/zyronchain-$VALIDATOR_LABEL"\nREPO="$ROOT/repo"\nmkdir -p "$ROOT"\nif [ ! -d "$REPO/.git" ]; then\n  git clone ${shellQuote(REPO_URL)} "$REPO"\nfi\ncd "$REPO"\ngit fetch --quiet origin\ngit checkout --detach ${shellQuote(RELEASE_REF)}\ncd l1\nnpm ci\nnpm run build`;

  const identityScript = (platform, label) => `#!/usr/bin/env bash
set -euo pipefail

# ZyronChain validator identity launcher
# Generated by https://zyronchain.com/validator.html
VALIDATOR_LABEL=${shellQuote(label)}
RELEASE_REF=${shellQuote(RELEASE_REF)}

${platformBootstrap(platform)}
${nodeVersionCheck}
${repoSetup}

umask 077
PASSWORD_FILE="$ROOT/validator.password"
KEY_FILE="$ROOT/validator.json"

if [ -e "$KEY_FILE" ]; then
  echo "Refusing to overwrite existing validator key: $KEY_FILE" >&2
  exit 1
fi

read -r -s -p "Create validator password (12+ characters): " ZYRON_PASSWORD
echo
if [ "\${#ZYRON_PASSWORD}" -lt 12 ]; then
  echo "Password must contain at least 12 characters." >&2
  unset ZYRON_PASSWORD
  exit 1
fi
printf '%s\\n' "$ZYRON_PASSWORD" > "$PASSWORD_FILE"
unset ZYRON_PASSWORD
chmod 600 "$PASSWORD_FILE"

node dist/src/cli.js keygen --out "$KEY_FILE" --password-file "$PASSWORD_FILE"
chmod 600 "$KEY_FILE"

cat <<EOF

ZyronChain validator identity created.
Directory: $ROOT
Release:   $RELEASE_REF

SHARE ONLY the public address and public key printed above.
NEVER share:
  $KEY_FILE
  $PASSWORD_FILE

Next: give your public information to the testnet coordinator and obtain the common genesis.json plus PeerId-pinned peer list.
EOF
`;

  const parsePeers = (text) => {
    const peers = String(text || '').split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
    for (const peer of peers) {
      if (!/^\/(ip4|ip6|dns4|dns6)\/.+\/tcp\/\d+\/p2p\/[A-Za-z0-9]+$/.test(peer)) {
        throw new Error(`Invalid PeerId-pinned multiaddr: ${peer}`);
      }
    }
    return [...new Set(peers)];
  };

  const parseGenesis = (text) => {
    const raw = String(text || '').trim();
    if (!raw) throw new Error('Paste the common genesis.json first.');
    if (raw.length > 2_000_000) throw new Error('Genesis JSON is unexpectedly large.');
    let parsed;
    try { parsed = JSON.parse(raw); } catch { throw new Error('Genesis is not valid JSON.'); }
    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) throw new Error('Genesis must be a JSON object.');
    if (typeof parsed.chainId !== 'string' || !parsed.chainId.trim()) throw new Error('Genesis is missing chainId.');
    return { raw: JSON.stringify(parsed, null, 2), chainId: parsed.chainId };
  };

  const networkScript = ({ platform, label, genesis, peers, p2pPort, rpcPort, dataDir }) => {
    const genesisB64 = encodeBase64Utf8(genesis.raw);
    const commandArgs = [
      '  --genesis "$GENESIS_FILE"',
      '  --data "$DATA_DIR"',
      '  --host 127.0.0.1',
      '  --port "$RPC_PORT"',
      '  --validator-key "$KEY_FILE"',
      '  --p2p-listen "/ip4/0.0.0.0/tcp/$P2P_PORT"',
      ...peers.map((peer) => `  --p2p-peer ${shellQuote(peer)}`)
    ].join(' \\\n');

    return `#!/usr/bin/env bash
set -euo pipefail

# ZyronChain friends/private-testnet validator launcher
# Generated by https://zyronchain.com/validator.html
# Chain: ${genesis.chainId}
VALIDATOR_LABEL=${shellQuote(label)}
RELEASE_REF=${shellQuote(RELEASE_REF)}
P2P_PORT=${p2pPort}
RPC_PORT=${rpcPort}
DATA_DIR_NAME=${shellQuote(dataDir)}

${platformBootstrap(platform)}
${nodeVersionCheck}
${repoSetup}

KEY_FILE="$ROOT/validator.json"
PASSWORD_FILE="$ROOT/validator.password"
GENESIS_FILE="$ROOT/genesis.json"
DATA_DIR="$ROOT/$DATA_DIR_NAME"

[ -f "$KEY_FILE" ] || { echo "Missing $KEY_FILE. Run the identity launcher first." >&2; exit 1; }
[ -f "$PASSWORD_FILE" ] || { echo "Missing $PASSWORD_FILE. Run the identity launcher first." >&2; exit 1; }
chmod 600 "$KEY_FILE" "$PASSWORD_FILE"
mkdir -p "$DATA_DIR"

GENESIS_B64=${shellQuote(genesisB64)}
export GENESIS_B64 GENESIS_FILE
node - <<'NODE'
const fs = require('node:fs');
const raw = Buffer.from(process.env.GENESIS_B64, 'base64').toString('utf8');
const parsed = JSON.parse(raw);
if (!parsed || typeof parsed.chainId !== 'string') throw new Error('invalid genesis');
fs.writeFileSync(process.env.GENESIS_FILE, JSON.stringify(parsed, null, 2) + '\\n', { mode: 0o644 });
NODE
unset GENESIS_B64

export ZYRON_KEYSTORE_PASSWORD_FILE="$PASSWORD_FILE"

cat <<EOF
Starting ZyronChain validator
Chain:       ${genesis.chainId}
Release:     $RELEASE_REF
RPC:         127.0.0.1:$RPC_PORT (local only)
P2P:         0.0.0.0:$P2P_PORT
Data:        $DATA_DIR
Peer count:  ${peers.length}

Only expose TCP $P2P_PORT to other validators. Do not publicly expose RPC $RPC_PORT.
Press Ctrl+C for a clean shutdown.
EOF

exec node dist/src/cli.js node \\
${commandArgs}
`;
  };

  const setStatus = (element, message, error = false) => {
    if (!element) return;
    element.textContent = message;
    element.classList.toggle('error', error);
  };

  const showOutput = (output, pre, script) => {
    if (!output || !pre) return;
    pre.textContent = script;
    output.hidden = false;
    output.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
  };

  $('identity-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const status = $('identity-status');
    const label = cleanLabel($('validator-label')?.value);
    const platform = $('identity-platform')?.value || 'linux';
    const script = identityScript(platform, label);
    showOutput($('identity-output'), $('identity-script'), script);
    setStatus(status, `Ready for ${label}. Private key will be generated locally.`);
  });

  $('network-form')?.addEventListener('submit', (event) => {
    event.preventDefault();
    const status = $('network-status');
    try {
      const label = cleanLabel($('validator-label')?.value);
      const platform = $('network-platform')?.value || 'linux';
      const p2pPort = validPort($('p2p-port')?.value);
      const rpcPort = validPort($('rpc-port')?.value);
      const dataDir = cleanLabel($('data-dir')?.value || 'data');
      if (!p2pPort || !rpcPort) throw new Error('Ports must be between 1024 and 65535.');
      if (p2pPort === rpcPort) throw new Error('P2P and RPC ports must be different.');
      const genesis = parseGenesis($('genesis-json')?.value);
      const peers = parsePeers($('peer-list')?.value);
      const script = networkScript({ platform, label, genesis, peers, p2pPort, rpcPort, dataDir });
      showOutput($('network-output'), $('network-script'), script);
      setStatus(status, `Validated ${genesis.chainId}; ${peers.length} explicit peer(s).`);
    } catch (error) {
      $('network-output').hidden = true;
      setStatus(status, error instanceof Error ? error.message : 'Unable to build validator script.', true);
    }
  });

  const copyText = async (id, button) => {
    const target = $(id);
    if (!target) return;
    try {
      await navigator.clipboard.writeText(target.textContent || '');
      const old = button.textContent;
      button.textContent = 'Copied';
      setTimeout(() => { button.textContent = old; }, 1300);
    } catch {
      button.textContent = 'Select & copy';
    }
  };

  document.querySelectorAll('[data-copy]').forEach((button) => {
    button.addEventListener('click', () => copyText(button.dataset.copy, button));
  });

  const downloadScript = (kind) => {
    const target = kind === 'identity' ? $('identity-script') : $('network-script');
    if (!target?.textContent) return;
    const name = kind === 'identity' ? 'zyron-validator-identity.sh' : 'zyron-validator-start.sh';
    const blob = new Blob([target.textContent], { type: 'text/x-shellscript;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = name;
    document.body.appendChild(link);
    link.click();
    link.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  };

  document.querySelectorAll('[data-download]').forEach((button) => {
    button.addEventListener('click', () => downloadScript(button.dataset.download));
  });

  const releaseField = $('release-ref');
  if (releaseField) releaseField.value = RELEASE_REF;
})();
